export function studentData() {
  return [
    {
      classId: "6",
      classTitle: "Six",
      students: [
        {
          id: 1,
          avatar: "/avatar/avatar (1).jpg",
          studentName: "Maruf",
          scores: "A+",
          percentage: "80%",
        },
        {
          id: 2,
          avatar: "/avatar/avatar (2).jpg",
          studentName: "Saif",
          scores: "A",
          percentage: "70%",
        },
        {
          id: 3,
          avatar: "/avatar/avatar (3).jpg",
          studentName: "Foysal",
          scores: "A-",
          percentage: "60%",
        },
        {
          id: 4,
          avatar: "/avatar/avatar (4).jpg",
          studentName: "Nusrat",
          scores: "B",
          percentage: "50%",
        },
        {
          id: 5,
          avatar: "/avatar/avatar (5).jpg",
          studentName: "Abrar",
          scores: "C",
          percentage: "40%",
        },
        {
          id: 6,
          avatar: "/avatar/avatar (6).jpg",
          studentName: "Rayhan",
          scores: "F",
          percentage: "30%",
        },
        {
          id: 7,
          avatar: "/avatar/avatar (7).jpg",
          studentName: "Alif",
          scores: "F",
          percentage: "20%",
        },
        {
          id: 8,
          avatar: "/avatar/avatar (8).jpg",
          studentName: "Rakib",
          scores: "A+",
          percentage: "90%",
        },
        {
          id: 9,
          avatar: "/avatar/avatar (9).jpg",
          studentName: "Abir",
          scores: "A+",
          percentage: "80%",
        },
        {
          id: 10,
          avatar: "/avatar/avatar (10).jpg",
          studentName: "Fahim",
          scores: "A+",
          percentage: "100%",
        },
      ],
    },
    {
      classId: "7",
      classTitle: "Seven",
      students: [
        {
          id: 1,
          avatar: "/avatar/avatar (11).jpg",
          studentName: "Tanvir",
          scores: "A+",
          percentage: "90%",
        },
        {
          id: 2,
          avatar: "/avatar/avatar (12).jpg",
          studentName: "Riyad",
          scores: "A+",
          percentage: "80%",
        },
        {
          id: 3,
          avatar: "/avatar/avatar (13).jpg",
          studentName: "Sadia",
          scores: "A",
          percentage: "70%",
        },
        {
          id: 4,
          avatar: "/avatar/avatar (14).jpg",
          studentName: "Ariful",
          scores: "A-",
          percentage: "60%",
        },
        {
          id: 5,
          avatar: "/avatar/avatar (15).jpg",
          studentName: "Jahan",
          scores: "B",
          percentage: "50%",
        },
        {
          id: 6,
          avatar: "/avatar/avatar (16).jpg",
          studentName: "Rizwan",
          scores: "C",
          percentage: "40%",
        },
        {
          id: 7,
          avatar: "/avatar/avatar (17).jpg",
          studentName: "Saira",
          scores: "F",
          percentage: "30%",
        },
        {
          id: 8,
          avatar: "/avatar/avatar (18).jpg",
          studentName: "Ayan",
          scores: "F",
          percentage: "20%",
        },
        {
          id: 9,
          avatar: "/avatar/avatar (19).jpg",
          studentName: "Karim",
          scores: "F",
          percentage: "10%",
        },
        {
          id: 10,
          avatar: "/avatar/avatar (20).jpg",
          studentName: "Rishad",
          scores: "A+",
          percentage: "100%",
        },
      ],
    },
    {
      classId: "8",
      classTitle: "Eight",
      students: [
        {
          id: 1,
          avatar: "/avatar/avatar (21).jpg",
          studentName: "Tanvir",
          scores: "A+",
          percentage: "90%",
        },
        {
          id: 2,
          avatar: "/avatar/avatar (22).jpg",
          studentName: "Riyad",
          scores: "A+",
          percentage: "80%",
        },
        {
          id: 3,
          avatar: "/avatar/avatar (23).jpg",
          studentName: "Sadia",
          scores: "A",
          percentage: "70%",
        },
        {
          id: 4,
          avatar: "/avatar/avatar (24).jpg",
          studentName: "Ariful",
          scores: "A-",
          percentage: "60%",
        },
        {
          id: 5,
          avatar: "/avatar/avatar (25).jpg",
          studentName: "Jahan",
          scores: "B",
          percentage: "50%",
        },
        {
          id: 6,
          avatar: "/avatar/avatar (26).jpg",
          studentName: "Rizwan",
          scores: "C",
          percentage: "40%",
        },
        {
          id: 7,
          avatar: "/avatar/avatar (27).jpg",
          studentName: "Saira",
          scores: "D",
          percentage: "30%",
        },
        {
          id: 8,
          avatar: "/avatar/avatar (28).jpg",
          studentName: "Ayan",
          scores: "F",
          percentage: "32%",
        },
        {
          id: 9,
          avatar: "/avatar/avatar (29).jpg",
          studentName: "Karim",
          scores: "F",
          percentage: "20%",
        },
        {
          id: 10,
          avatar: "/avatar/avatar (30).jpg",
          studentName: "Rishad",
          scores: "A+",
          percentage: "100%",
        },
      ],
    },
    {
      classId: "9",
      classTitle: "Nine",
      students: [
        {
          id: 1,
          avatar: "/avatar/avatar (31).jpg",
          studentName: "Saiful",
          scores: "A",
          percentage: "72%",
        },
        {
          id: 2,
          avatar: "/avatar/avatar (32).jpg",
          studentName: "Rahim",
          scores: "A-",
          percentage: "63%",
        },
        {
          id: 3,
          avatar: "/avatar/avatar (33).jpg",
          studentName: "Tania",
          scores: "B",
          percentage: "54%",
        },
        {
          id: 4,
          avatar: "/avatar/avatar (34).jpg",
          studentName: "Anika",
          scores: "C",
          percentage: "45%",
        },
        {
          id: 5,
          avatar: "/avatar/avatar (35).jpg",
          studentName: "Amir",
          scores: "D",
          percentage: " 36%",
        },
        {
          id: 6,
          avatar: "/avatar/avatar (36).jpg",
          studentName: "Sabrina",
          scores: "F",
          percentage: "27%",
        },
        {
          id: 7,
          avatar: "/avatar/avatar (37).jpg",
          studentName: "Rizvi",
          scores: "F",
          percentage: "18%",
        },
        {
          id: 8,
          avatar: "/avatar/avatar (38).jpg",
          studentName: "Salma",
          scores: "F",
          percentage: "20%",
        },
        {
          id: 9,
          avatar: "/avatar/avatar (39).jpg",
          studentName: "Hasan",
          scores: "F",
          percentage: "30%",
        },
        {
          id: 10,
          avatar: "/avatar/avatar (40).jpg",
          studentName: "Rakib",
          scores: "A+",
          percentage: "81%",
        },
      ],
    },
  ];
}
